Fix compiling with wxWidgets 3.3
wxWidgets 3.3 has stopped defining in global scope all operators
including "+" on wx types, causing some string concatenations to fail.

All the constants from ImGui used by marker_by_type() are of type
wchar_t. Stop returning them as type char.

PrusaSlicer-version_2.9.3/src/slic3r/GUI/Search.cpp:253:62: error: no match for ‘operator+’ (operand types are ‘char’ and ‘const std::wstring’ {aka ‘const std::__cxx11::basic_string<wchar_t>’})
  253 |         return  marker_by_type(opt.type, printer_technology) +
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
      |                               |
      |                               char
  254 |                 opt.category_local + sep +
      |                 ~~~~~~~~~~~~~~~~~~
      |                     |
      |                     const std::wstring {aka const std::__cxx11::basic_string<wchar_t>}